import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BackButton from "@/components/BackButton/BackButton";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-row justify-center items-center">
          <BackButton />
          <h1 className="text-center text-white mb-0 whitespace-nowrap xs:text-sm">
            G H O S T M Y R E C R U I T E R .
          </h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
